In [1]:
import numpy as np
import math
from ipycanvas import Canvas, hold_canvas
from time import sleep

In [2]:
CANVAS_HEIGTH = 200
CANVAS_WIDTH = 200
CANVAS_X_OFFSET = CANVAS_WIDTH / 2
CANVAS_Y_OFFSET = CANVAS_HEIGTH / 2
CANVAS_XLIM = (-CANVAS_X_OFFSET, CANVAS_WIDTH-CANVAS_X_OFFSET)
CANVAS_YLIM = (-CANVAS_Y_OFFSET, CANVAS_HEIGTH-CANVAS_Y_OFFSET)

In [3]:
def draw_vertices(canvas:Canvas, vertices):
    for i in range(1, len(vertices)):
        canvas.stroke_line(
            int(vertices[i-1,0] + CANVAS_X_OFFSET), 
            int(canvas.height - vertices[i-1,1] - 1 - CANVAS_Y_OFFSET), 
            int(vertices[i,0] + CANVAS_X_OFFSET), 
            int(canvas.height - vertices[i,1]) - 1 - CANVAS_Y_OFFSET)

def rotate_z(vertices, a):
    m = np.array([
        [ math.cos(a), math.sin(a), 0, 0],
        [-math.sin(a), math.cos(a), 0, 0],
        [ 0,         0,         1, 0],
        [ 0,         0,         0, 1],
    ])
    return vertices @ m

def rotate_y(vertices, a):
    m = np.array([
        [math.cos(a), 0, -math.sin(a), 0],
        [0, 1, 0, 0],
        [math.sin(a), 0, math.cos(a), 0],
        [0, 0, 0, 1]
    ])
    return vertices @ m

def rotate_z(vertices, a):
    m = np.array([
        [math.cos(a), math.sin(a), 0, 0],
        [-math.sin(a), math.cos(a), 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])
    return vertices @ m

def translate(vertices, dx, dy, dz):
    m = np.array([
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [dx, dy, dz, 1],
    ])
    return vertices @ m

def scale(vertices, sx, sy, sz):
    m = np.array([
        [sx, 0, 0, 0],
        [0, sy, 0, 0],
        [0, 0, sz, 0],
        [0, 0, 0, 1]
    ])
    return vertices @ m

In [4]:
obj_vertices = np.array([
    [-50, -50, 1, 1],
    [-50,  50, 1, 1],
    [ 50,  50, 1, 1],
    [ 50, -50, 1, 1],
    [-50, -50, 1, 1]]
)

In [5]:
canvas = Canvas(height=CANVAS_HEIGTH, width=CANVAS_WIDTH)
display(canvas)
for s in range(0, 360 + 1):
    with hold_canvas():
        canvas.clear()
        draw_vertices(canvas, rotate_z(obj_vertices, math.radians(s)))
    sleep(0.02)

Canvas(height=200, width=200)

In [6]:
print(obj_vertices)
translate(obj_vertices, 2, 1, 0)

[[-50 -50   1   1]
 [-50  50   1   1]
 [ 50  50   1   1]
 [ 50 -50   1   1]
 [-50 -50   1   1]]


array([[-48, -49,   1,   1],
       [-48,  51,   1,   1],
       [ 52,  51,   1,   1],
       [ 52, -49,   1,   1],
       [-48, -49,   1,   1]])

In [7]:
canvas = Canvas(height=CANVAS_HEIGTH, width=CANVAS_WIDTH)
display(canvas)

dx = 2
dy = 1
obj = obj_vertices

for s in range(500):
    obj = translate(obj, dx, dy, 0)
    ymax = np.max(obj[:,1])
    zmax = np.max(obj[:,2])
    if(np.min(obj[:,0])<=CANVAS_XLIM[0] or np.max(obj[:,0])>=CANVAS_XLIM[1]):
        dx = -dx
    if(np.min(obj[:,1])<=CANVAS_YLIM[0] or np.max(obj[:,1])>=CANVAS_YLIM[1]):
        dy = -dy
    with hold_canvas():
        canvas.clear()
        draw_vertices(canvas, obj)
    sleep(0.02)

Canvas(height=200, width=200)