In [20]:
from ipycanvas import Canvas
canvas = Canvas(width=200, height=200)
canvas

Canvas(height=200, width=200)

In [21]:
from ipycanvas import MultiCanvas

# Create a multi-layer canvas with 4 layers
multi_canvas = MultiCanvas(4, width=200, height=200)
multi_canvas[0]  #  Access first layer (background)
multi_canvas[3]  #  Access last layer (foreground)
multi_canvas

MultiCanvas(height=200, width=200)

In [22]:
canvas.width = 300
canvas.height = 600

In [23]:
from ipycanvas import Canvas

canvas = Canvas(width=200, height=200)

canvas.fill_rect(25, 25, 100, 100)
canvas.clear_rect(45, 45, 60, 60)
canvas.stroke_rect(50, 50, 50, 50)

canvas

Canvas(height=200, width=200)

In [24]:
import numpy as np

from ipycanvas import Canvas

n_particles = 100_000

x = np.array(np.random.rayleigh(250, n_particles), dtype=np.int32)
y = np.array(np.random.rayleigh(250, n_particles), dtype=np.int32)
size = np.random.randint(1, 3, n_particles)

canvas = Canvas(width=800, height=500)

canvas.fill_style = [255,0,0,0]
canvas.fill_rects(x, y, size)

canvas

TraitError: The 'fill_style' trait of a Canvas instance expected a valid HTML color or a _CanvasGradient or a Pattern, not the list [255, 0, 0, 0].

In [ ]:
from ipycanvas import Canvas

canvas = Canvas(width=200, height=200)

canvas.fill_style = "#63934e"
canvas.stroke_style = "#4e6393"
canvas.line_width = 5
canvas.fill_polygon([(20, 20), (180, 20), (100, 150)])
canvas.stroke_polygon([(20, 20), (180, 20), (100, 150)])

canvas

Canvas(height=200, width=200)

In [ ]:
canvas = Canvas(width=200, height=200)
canvas.stroke_line(0,0,100,100)
canvas

Canvas(height=200, width=200)

In [ ]:
from time import sleep

from ipycanvas import Canvas, hold_canvas

canvas = Canvas()
display(canvas)

# Number of steps in your animation
steps_number = 200

for i in range(steps_number):
    with hold_canvas():
        # Clear the old animation step
        canvas.clear()

        canvas.stroke_line(i,i,100,100)

    # Animation frequency ~50Hz = 1./50. seconds
    sleep(0.02)

Canvas()

In [ ]:
import numpy as np

from ipycanvas import Canvas

x = np.linspace(-1, 1, 600)
y = np.linspace(-1, 1, 600)

x_grid, y_grid = np.meshgrid(x, y)

blue_channel = np.array(np.sin(x_grid**2 + y_grid**2) * 255, dtype=np.int32)
red_channel = np.zeros_like(blue_channel) + 200
green_channel = np.zeros_like(blue_channel) + 50

image_data = np.stack((red_channel, blue_channel, green_channel), axis=2)

canvas = Canvas(width=image_data.shape[0], height=image_data.shape[1])
canvas.put_image_data(image_data, 0, 0)

canvas

Canvas(height=600, width=600)

In [26]:
image_data = np.stack((red_channel, blue_channel, green_channel), axis=2)
image_data

array([[[200, 231,  50],
        [200, 232,  50],
        [200, 233,  50],
        ...,
        [200, 233,  50],
        [200, 232,  50],
        [200, 231,  50]],

       [[200, 232,  50],
        [200, 233,  50],
        [200, 233,  50],
        ...,
        [200, 233,  50],
        [200, 233,  50],
        [200, 232,  50]],

       [[200, 233,  50],
        [200, 233,  50],
        [200, 234,  50],
        ...,
        [200, 234,  50],
        [200, 233,  50],
        [200, 233,  50]],

       ...,

       [[200, 233,  50],
        [200, 233,  50],
        [200, 234,  50],
        ...,
        [200, 234,  50],
        [200, 233,  50],
        [200, 233,  50]],

       [[200, 232,  50],
        [200, 233,  50],
        [200, 233,  50],
        ...,
        [200, 233,  50],
        [200, 233,  50],
        [200, 232,  50]],

       [[200, 231,  50],
        [200, 232,  50],
        [200, 233,  50],
        ...,
        [200, 233,  50],
        [200, 232,  50],
        [200, 231,  50]]

In [25]:
print(image_data)

[[[200 231  50]
  [200 232  50]
  [200 233  50]
  ...
  [200 233  50]
  [200 232  50]
  [200 231  50]]

 [[200 232  50]
  [200 233  50]
  [200 233  50]
  ...
  [200 233  50]
  [200 233  50]
  [200 232  50]]

 [[200 233  50]
  [200 233  50]
  [200 234  50]
  ...
  [200 234  50]
  [200 233  50]
  [200 233  50]]

 ...

 [[200 233  50]
  [200 233  50]
  [200 234  50]
  ...
  [200 234  50]
  [200 233  50]
  [200 233  50]]

 [[200 232  50]
  [200 233  50]
  [200 233  50]
  ...
  [200 233  50]
  [200 233  50]
  [200 232  50]]

 [[200 231  50]
  [200 232  50]
  [200 233  50]
  ...
  [200 233  50]
  [200 232  50]
  [200 231  50]]]
