In [21]:
import numpy as np

In [22]:
m = np.repeat('#ffffff',6).reshape((2,3))
m

array([['#ffffff', '#ffffff', '#ffffff'],
       ['#ffffff', '#ffffff', '#ffffff']], dtype='<U7')

In [23]:
m.shape

(2, 3)

In [24]:
m[1,2] = "xxxxx"
m

array([['#ffffff', '#ffffff', '#ffffff'],
       ['#ffffff', '#ffffff', 'xxxxx']], dtype='<U7')

In [25]:
m[:,:]='0000'
m

array([['0000', '0000', '0000'],
       ['0000', '0000', '0000']], dtype='<U7')

In [26]:
def point_dist(p1,p2):
    return np.sum(np.power(p1-p2, 2)) ** 0.5

In [27]:
point_dist(np.array([1,2]), np.array([2,3]))

1.4142135623730951

In [28]:
a = np.repeat(0, 2*3*3).reshape((2,3,3))
a[:,:,0] = 255
a[:,:,1] = 200
a[:,:,2] = 100
a

array([[[255, 200, 100],
        [255, 200, 100],
        [255, 200, 100]],

       [[255, 200, 100],
        [255, 200, 100],
        [255, 200, 100]]])

In [30]:
a[:,:,1]

array([[200, 200, 200],
       [200, 200, 200]])

In [35]:
from colour import Color
(np.array(Color("#d11d4d").rgb)*255).astype('int')

array([209,  29,  76])

In [36]:
c = [1,2,3,4,5]
[*c[:3],9]

[1, 2, 3, 9]